E commerce
abrarqa62/ngx-admin-cypress pull request #1
Opened 2022-06-10 15:48 UTC by abrarqa62

I did the fully automation of E-commerce page.

https://user-images.githubusercontent.com/106743757/173621843-f6a23a05-642f-4909-89a3-e9964e54810d.mp4

2022-06-13 11:55 UTC, hassanatdevsinc requested changes
Please add the screenshots and screen recordings folder in git ignore.
I have added comments please look into them. Do let me know if you have any questions Thanks

2022-06-13 11:55 UTC, hassanatdevsinc commented on cypress/integration/EcommerceAutomation.spec.js
> +    it("User is on Profit Card Section", () => {
Text in 'it' block should start with "Verify if "

2022-06-13 11:55 UTC, hassanatdevsinc commented on cypress/integration/EcommerceAutomation.spec.js
> +        c.click(pointXaxis1, PointYaxis1).wait(300);
please remove static waits from  test cases

2022-06-13 11:55 UTC, hassanatdevsinc commented on cypress/integration/EcommerceAutomation.spec.js
> +        NavigateTo.DropdownButtonEarning().click().should('be.visible');
NavigateTo.DropdownButtonEarning().click().should('be.visible'); in this line the assertion for be visible should be before click action

2022-06-13 11:55 UTC, hassanatdevsinc commented on cypress/integration/EcommerceAutomation.spec.js
> +          let e = cy.wrap($Earningcanvas);
let e = cy.wrap($Earningcanvas);
        cy.log($Earningcanvas.width());
        cy.log($Earningcanvas.height());
 As this is used in most of the test cases please create a function for it and use it in the test cases

2022-06-13 11:55 UTC, hassanatdevsinc commented on cypress/integration/EcommerceAutomation.spec.js
> +        e.click(10, 130).wait(300);
why do hardcoding values in the click use variables in it.

2022-06-13 11:55 UTC, hassanatdevsinc commented on cypress/support/page_objects/PageObjectsEcommerce.js
> +    return cy.get(".option-list");
why not used Data-test-id here?

2022-06-13 11:55 UTC, hassanatdevsinc commented on cypress/support/page_objects/PageObjectsEcommerce.js
> +    return cy.get(".option-list");
same as on line 31

2022-06-15 11:16 UTC, hassanatdevsinc approved these changes

2022-06-15 11:20 UTC, merged

2022-06-15 18:58 UTC, abrarqa62 commented on cypress/support/page_objects/PageObjectsEcommerce.js
> +    return cy.get(".option-list");
Done

2022-06-15 18:58 UTC, abrarqa62 commented on cypress/support/page_objects/PageObjectsEcommerce.js
> +    return cy.get(".option-list");
Done

2022-06-15 18:59 UTC, abrarqa62 commented on cypress/integration/EcommerceAutomation.spec.js
> +        NavigateTo.DropdownButtonEarning().click().should('be.visible');
Done

2022-06-15 18:59 UTC, abrarqa62 commented on cypress/integration/EcommerceAutomation.spec.js
> +        c.click(pointXaxis1, PointYaxis1).wait(300);
Done